### PR TITLE
Added mutex unlockAll

### PR DESCRIPTION
**Pull request by XeniaSiskaki**
Add possibility for user to release all locks  for #14

### CODE REVIEW

**Comment by ronkorving** [comment]
Thanks @XeniaSiskaki !

Sorry for being so nitpicky about naming, I hope it doesn't hurt your motivation in your contribution. Changing it later would constitute a breaking change however, so I wanna make sure we get it right on the first try.

I think `unlockAll` is not technically correct. The mutex can only be locked zero or one time. Its state is very boolean. Your implementation of `unlockAll` does what we agreed upon in #14, which implies it doesn't actually unlock the mutex. You still need to call `unlock` to do that. This is good, but that does mean that `unlockAll` to me is a bit confusing a name.

What it does is, it forgets all waiting callbacks, so that after a call to `unlock` they will not be invoked. That's why in #14 I suggested calling it `reset`, which arguably is also not a great name. Suggestions very welcome, but IMHO `unlockAll` is a little bit confusing. Thoughts?

**Comment by ronkorving** [comment]
Sure, that works for me 👍

**Comment by XeniaSiskaki** [comment]
Sorry, took me longer to get back to it!

**Comment by ronkorving** [comment]
No worries, thanks for your contribution!

**Comment by XeniaSiskaki** [comment]
@ronkorving when do you think this will make it into npm?

**Pull request merged**
